version: "3.8"
services:
  db:
    image: "ankane/pgvector:v0.5.1"
    environment:
      PG_MAJOR: 15
      PGPASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - "forum_magnum_db:/var/lib/postgresql/data"
      # - "./schema/accepted_schema.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
  web:
    build: .
    depends_on:
      - "db"
    environment:
      PG_HOST: "db"
      PG_URL: "${PG_URL}"
      ELASTIC_URL: "${ELASTIC_URL:-https://elastic:9200}"
      PORT: "3000"
    ports:
      - "${PORT:-3000}:3000"
    profiles:
      - web
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    working_dir: "/usr/share/elasticsearch"
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      discovery.type: "single-node"
      xpack.security.enabled: "true"
    volumes:
      - "elastic_db:/usr/share/elasticsearch/data"
    profiles:
      - elastic
volumes:
  forum_magnum_db:
    driver: local
  elastic_db:
    driver: local
