version: "3.8"
services:
  db:
    image: "ankane/pgvector:v0.5.1"
    environment:
      PG_MAJOR: 15
      PGPASSWORD: "${PG_PASSWORD:-secret}"
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-secret}"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - "forum_magnum_db:/var/lib/postgresql/data"
      - "./schema/accepted_schema.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
volumes:
  forum_magnum_db:
    driver: local
