version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: forum_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d forum_development"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: