name: Power Cycle Elasticsearch

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  powercycle:
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Powercycle Elasticsearch droplet
        run: "doctl compute droplet-action power-cycle --wait ${{ secrets.ELASTICSEARCH_DROPLET_ID }}"
